### ISSUE TITLE
Please invite me to the Camunda Community

### ISSUE THREAD

**Issue by sagarsam51** [camunda-community-hub/community#106]
Hi all,

Please invite me to join the camunda community. I'm looking to contribute code to spring-zeebe, initially related to customization of the ZeebeClient's channel to support mutual TLS. I've agreed to the CLA as well and will be contributing on behalf of my employer.

Thanks,
Sagar Samant

**Comment by xomiamoore** [comment]
Hi @sagarsam51, is there a reason you copied the text from this Issue? Just making sure you aren't a bot :) https://github.com/camunda-community-hub/community/issues/105

**Comment by sagarsam51** [comment]
I belong to the same employer as Rob. We're both working on the same feature :)

**Comment by sagarsam51** [comment]
Hello, just following up on the above.

**Comment by xomiamoore** [comment]
Sorry for the delay, sent an invite -- let me know if you need anything else :) Welcome!

**Comment by sagarsam51** [comment]
Thank you very much :)
