### ISSUE TITLE
Camunda Modeler Setup Manager (on a Mac)

### ISSUE THREAD

**Issue by pme123** [camunda-community-hub/community#12]
# Camunda Community Hub Extension Proposal

### Extension description

This project helps you with the tasks to setup the Camunda Modeler.

- Install/ Update the Modeler.
- Install/ Update useful Plugins.
- Installl/ Update the Script Plugin (extra Task as it is huge😳)

https://github.com/pme123/camunda-modeler-plugin-manager

### Suggested use case

Installing und updating Modeler Plugins is quite cumbersome. So why not automate this process.

### Configuration

None
### Dependencies

[Ammonite](http://ammonite.io)
### Issues/Challenges

None
### Extension lifecycle

Ready to use
### Maintainer Needed?

No

**Comment by pme123** [comment]
Hi @celanthe 
Ok done, thanks for accepting:).

**Comment by celanthe** [comment]
@pme123 Fantastic! I'll go ahead and close this issue and thank you again! :D
