### ISSUE TITLE
Camunda Community Hub Collaborator

### ISSUE THREAD

**Issue by MiguelitoEnrique** [camunda-community-hub/community#13]
Hi there,

I would like to get collaborator access to the Camunda Community Hub in order to migrate JIT Camunda Plugins repository into the Community Hub (https://github.com/jit-open).

Thanks

Miguel

**Comment by celanthe** [comment]
Hi @MiguelitoEnrique! Fantastic, I'll send you an invitation ASAP! From there, you should be able to follow the instructions for migrating the repository into the Community Hub. :D
