### ISSUE TITLE
ENGINE-09005 Could not parse BPMN process. Errors: 

### ISSUE THREAD

**Issue by thamarathamara** [camunda-community-hub/community#141]
When installing camunda 7, downloading run and tomcat, when publishing a process, the following error occurs:

**ENGINE-09005 Could not parse BPMN process. Errors: 
* src-resolve: Cannot resolve the name 'extension' to a(n) 'element declaration' component. | resource test.bpmn | line 15 | column 70
* src-resolve: Cannot resolve the name 'rootElement' to a(n) 'element declaration' component. | resource test.bpmn | line 16 | column 72
* src-resolve: Cannot resolve the name 'bpmndi:BPMNDiagram' to a(n) 'element declaration' component. | resource test.bpmn | line 17 | column 79
* src-resolve: Cannot resolve the name 'relationship' to a(n) 'element declaration' component. | resource test.bpmn | line 18 | column 73
* cvc-complex-type.2.4.a: Invalid content was found starting with element '{"http://www.omg.org/spec/BPMN/20100524/MODEL":process}'. One of '{"http://www.omg.org/spec/BPMN/20100524/MODEL":import}' is expected. | resource test.bpmn | line 3 | column 92 [ deploy-error ]**

How to solve?

**Comment by xomiamoore** [comment]
Hey @thamarathamara, please ask your question on the [Camunda forum ](https://forum.camunda.io/)as this is not a support channel. Thank you!
