### ISSUE TITLE
Camunda forms example repository

### ISSUE THREAD

**Issue by christian-konrad** [camunda-community-hub/community#142]
# Camunda Community Hub extension proposal

camunda-forms-examples

### Extension description

A Camunda Forms example repository to showcase what Camunda Forms can do, to provide starting points for customers, and link to them in the docs.

### Suggested use case

Understand form editor capabilities, discover use cases, find a way to get started quickly.

### Configuration

No config needed—just form editor files.

### Dependencies

None

### Issues/Challenges

None

### Extension lifecycle

-

### Additional context

-

### Maintainer needed?

No

**Comment by christian-konrad** [comment]
Hi @xomiamoore , can you help me set up the repo, or can I do it myself? Thank you!

**Comment by christian-konrad** [comment]
I created it: https://github.com/camunda-community-hub/camunda-forms-example

**Comment by xomiamoore** [comment]
Hey @christian-konrad, sorry for the delay, I was out sick 😷 Looks like you got everything figured out but let me or @camunda-community-hub/devrel  know if we can help with anything else!
