### ISSUE TITLE
Extension Maintainer Proposal for camunda-modeler-template-generator

### ISSUE THREAD

**Issue by matthias-petri** [camunda-community-hub/community#157]
# Camunda Community Hub extension maintainer proposal

I am currently the maintainer of the repository: https://github.com/camunda-community-hub/camunda-modeler-template-generator and I would like to ask you to make one of my team members a maintainer of this repository as well, so that he has access to merging pull requests etc.:

https://github.com/sascha-hanss-76

Thank you very much!

I agree that I have either: 
- [ ] Made a good faith effort to contact the extension's original maintainer.
- [x] Successfully reached the extension’s original maintainer and they are in agreement that I am to maintain this extension moving forward.
- [x] I will update the documentation accordingly to reflect my status as this extension's Maintainer.
- [x] I have read the **Camunda Community Hub** [documentation](https://github.com/Camunda-Community-Hub/community).
- [x] I have read the Camunda Community Hub **abandoned extension Maintainer proposal** documentation.
- [x] I will /assign myself this issue, and add the relevant [issue labels](https://github.com/camunda-community-hub/community/blob/main/issue-triage.md) to it if they are not automatically generated by Probot.
- [x] I will tag @camunda-community-hub/devrel in a new comment on this issue if 30 days have passed since my pull request was opened and I haven't received a response from the extension's original maintainer.

**Comment by xomiamoore** [comment]
Hey @matthias-petri, thanks for waiting during vacation season. I have sent a request to @sascha-hanss-76 to become co-maintainer :) Let me know if you need anything else!
