### ISSUE TITLE
Repository Proposal: Connector Workshop CamundaCon NY

### ISSUE THREAD

**Issue by Hafflgav** [camunda-community-hub/community#158]
# Camunda Community Hub extension proposal

### Extension description
As I am giving a workshop during CamundaCon in New York this year, I want to create a repository for guiding the audience through the such. The topic is focused on getting started with sustainable connector development. 
This repository will contain the description for the workshop as well as the solutions and implementations. 
(The workshop will be delivered with @crobbins215) 

### Suggested use case
It is going to be used for learning purposes only. 

### Configuration
Not applicable as of now. 

### Dependencies
Java 21 or higher, Spring Boot 3.6

### Extension lifecycle
The contents of this repository will get updated before and after the workshop took place. If it is going to take place more than once it will be maintained further onwards, otherwise not. 

### Maintainer needed?
I can happily be the maintainer I would be also volunteering to help people who are doing this workshop asynchronously after it took place.

**Comment by xomiamoore** [comment]
Hey @Hafflgav, happy to set this up for you! What do you want the repo to be named?

**Comment by Hafflgav** [comment]
Hey @xomiamoore, 
thank you! :) 

Ideally you can name it "future-proof-connectors-workshop" or "camunda-connector-workshop". 
Whatever you prefer. 👍 

Cheers

**Comment by xomiamoore** [comment]
@Hafflgav Here you go! Added you and @crobbins215 as maintainers https://github.com/camunda-community-hub/future-proof-connectors-workshop 

Let me know if you need anything else!

**Comment by Hafflgav** [comment]
Thank you! 🤩 
Appreciate the fast provisioning of the repo!
