### ISSUE TITLE
New repository named `camunda-8-init-and-backup`

### ISSUE THREAD

**Issue by upgradingdave** [camunda-community-hub/community#161]
# Camunda Community Hub extension proposal

### Extension description

Provide bash scripts that can be run independent of Camunda 8 which will initialize and backup Elasticsearch objects.

By default, the Camunda 8 applications will attempt to create Elasticsearch objects (such as [index templates](https://www.elastic.co/guide/en/elasticsearch/reference/current/index-templates.html)) during first start. Camunda applications also make use of Elasticsearch Snapshot Repositories and snapshot API's to run the official [Camunda Backup steps](https://docs.camunda.io/docs/self-managed/operational-guides/backup-restore/backup-and-restore/).  

These operations require [Elasticsearch cluster level access](https://docs.camunda.io/docs/self-managed/concepts/elasticsearch-privileges/). 

However, in some cases, because of security policies, it is not possible to grant the Camunda applications the necessary [elastic search cluster level](https://docs.camunda.io/docs/self-managed/concepts/elasticsearch-privileges/) access to initialize Elasticsearch Objects or perform backups. 

As a possible workaround to this problem, this project contains scripts that can be run independently of a Camunda 8 installation to initialize Elasticsearch Objects and create backups for Camunda 8 Zeebe, Operate, and Tasklist. 

Scripts for Optimize are currently not available.

### Suggested use case
Customers who are not able to grant C8 apps cluster level access to Elasticsearch can use this repo

### Configuration
We'll provide a complete README on how to use the scripts

### Dependencies
C8 SM installation and Elasticsearch

### Issues/Challenges
- Optimize currently cannot be run without granting es cluster level access. So this script will only work for Zeebe, Tasklist and Operate. 
- This script will not provide ability to upgrade ES schemas. 

### Extension lifecycle
Incubating

### Additional context
These scripts are being create to support an existing customer, however should be general enough for anyone to use. 

### Maintainer needed?
I can be the maintainer.

**Comment by xomiamoore** [comment]
Awesome! Here's the repo and you should have access, let me know if there's anything else you need! 

https://github.com/camunda-community-hub/camunda-8-init-and-backup
