### ISSUE TITLE
Camunda Cloud Self Managed Docker Compose file (Zeebe, Elasticsearch, Operate, Tasklist, IAM, IAM database, and Optimize)

### ISSUE THREAD

**Issue by superbeagle** [camunda-community-hub/community#21]
# Camunda Community Hub Extension Proposal

Hello, I'd like to put our internal project, creating a docker-compose file to stand up a complete CCSM (Zeebe, Elasticsearch, Operate, Tasklist, IAM, IAM database, and Optimize) locally for development, out into the community for others to use

### Extension description
The project can be found here:
https://github.com/camunda-consulting/ccsm

It allows folks who have docker-compose to quickly start a Cloud environment and get a better understanding of its value in an offline fashion. The topic of standing up a local environment does come up from time to time in Slack and the Forum in the community.  

### Suggested use case
For anybody who wants to explore CCSM

### Configuration
Configuration is explained in the readme

### Dependencies
Docker, Docker Compose

### Issues/Challenges
There could be issues depending on the versions of the applications used, if changed

### Extension lifecycle

camunda-cloud
### Additional Context

None

### Maintainer Needed?
No

**Comment by akeller** [comment]
Hey @superbeagle sounds great! Are you looking to transfer it into the Community Hub? I'll go ahead and get you access so we can move this forward.

**Comment by akeller** [comment]
Thanks for your contribution! https://github.com/camunda-community-hub/camunda-cloud-docker-compose
