### ISSUE TITLE
New Community Extension - camunda-bpm-monitor

### ISSUE THREAD

**Issue by bsorahan** [camunda-community-hub/community#23]
# Camunda Community Hub Extension Proposal

### Extension description
This extensions allows you to easily add application monitoring for your Camunda project on Spring Boot.

The extension creates [Micrometer](https://micrometer.io/) gauge and counter meters for Camunda's Process Instances, Incidents, User Tasks, and External Tasks. These metrics are exposed using Spring Boot's Actuator which provides a vendor-nuetral facade to expose metrics to many popular monitoring systems (i.e. Elastic, Prometheus). See [here](https://docs.spring.io/spring-boot/docs/current/reference/html/actuator.html#actuator.metrics).

Your chosen monitoring system can then use these metrics for monitoring, health checks and alarming.

### Suggested use case
Application monitoring, health checks, and alarming

### Configuration
1. Include the monitor extension dependency
``` xml
<dependency>
    <groupId>com.squashedbug.camunda.bpm.extension.monitor</groupId>
    <artifactId>camunda-bpm-spring-boot-monitor</artifactId>
    <version>0.1.7</version>
</dependency>
```
2. Add the `@EnableMonitoring` annotation to your application entrypoint class.
``` java
@SpringBootApplication
@com.squashedbug.camunda.bpm.monitor.EnableMonitoring
public class MyCamundaApp {

    public static void main(String[] args) {

        SpringApplication.run(MyCamundaApp.class, args);
    }

}

```

### Dependencies
Spring Boot

### Issues/Challenges
Monitoring system (such as Prometheus) is required to utilise the metrics that this extension provides.

### Extension lifecycle
Incubating

### Additional Context
The extension is currently in the repo here: https://github.com/bsorahan/camunda-bpm-monitor

### Maintainer Needed?
No

**Comment by celanthe** [comment]
Hi @bsorahan! Thank you so much for this wonderful new community extension proposal. We'd love to have it in the Community Hub. If you'd like to follow the instructions in the /community repository for transferring a repo in your personal account to another organization, that would be great!

Once the transfer is completed, if you could add an incubating lifecycle badge from the lifecycle.MD page to the repo's README, that would really help as well. If you need anything else, please don't hesitate to ask. Myself and the @camunda-community-hub/devrel team are happy to help. :)

**Comment by akeller** [comment]
Thank you! Transfer was successful and repo is available here - https://github.com/camunda-community-hub/camunda-bpm-monitor
