### ISSUE TITLE
New Community Extension - eze-java

### ISSUE THREAD

**Issue by Lzgabel** [camunda-community-hub/community#25]
# Camunda Community Hub Extension Proposal
Hi there,

I would like to join the Camunda Community Hub in order to migrate the [eze-java](https://github.com/Lzgabel/eze-java) repository.

A lightweight version of [Zeebe](https://github.com/camunda-cloud/zeebe) from [Camunda](https://camunda.com/). It bundles Zeebe's workflow engine including some required parts to a library that can be used by other projects.

Features:

* Support Zeebe clients and exporters
* Use RocksDB instead of the in-memory database

### Extension description

The project can be found here: https://github.com/Lzgabel/eze-java

### Suggested use case

None

### Configuration

Configuration is explained in the readme.

### Dependencies

Spring Boot

### Issues/Challenges

None

### Extension lifecycle

Zeebe

### Additional Context

None
### Maintainer Needed?

No

**Comment by akeller** [comment]
Hi @Lzgabel you should have a pending invitation in your GitHub inbox.

**Comment by Lzgabel** [comment]
Hi @akeller I'm in, thanks!
