### ISSUE TITLE
Dead links in release description

### ISSUE THREAD

**Issue by tmetzke** [camunda-community-hub/community#26]
The https://github.com/camunda-community-hub/community/blob/main/RELEASE.MD contains a couple of dead links, namely:

* https://github.com/camunda-community-hub/infrastructure
* https://github.com/camunda-community-hub/infrastructure#use-case-onboarding-a-new-community-hub-repository
* https://github.com/orgs/camunda-community-hub/teams/devrel

This makes it a bit inconvenient for maintainers to go through with the release process of an extension.

**Comment by akeller** [comment]
These are actually not dead links, but the infrastructure repo is private. I've reached out to understand if I can make this repo public. 

As for the devrel team link, I'll see how we can make that clear or easier. There is no reason that team needs to be private, but I'm not sure GitHub has a better way to communicate using `@camunda-community-hub/devrel` without linking to it.

**Comment by tmetzke** [comment]
Thanks, @akeller, for those insights 👍

**Comment by akeller** [comment]
@tmetzke I didn't realize you were not a part of the Camunda Community Hub! I've invited you as a member. This should give you access to the infrastructure repo and be able to see the devrel team link.

**Comment by akeller** [comment]
I also added a quick fix to the README you referenced

> You must be a member of the Camunda Community Hub to work with the Infrastructure repo.
