### ISSUE TITLE
C8 SaaS mock workers web application

### ISSUE THREAD

**Issue by marco-as-lopes** [camunda-community-hub/community#28]
# Camunda Community Hub Extension Proposal

### Extension description
Small web application where a user can upload a C8 SaaS credentials file and a BPMN file. The application will create mock workers for all service tasks in the BPMN file. All worker can then be configured to generate a error, execute for X amount of second, change return variable or just stop. The application can also start instances with a configurable cadence.

### Suggested use case
- Assisted onboarding (business can model and execute the process without worrying with service tasks implementation)
- Diagram testing
- Accelerator for PoCs

### Configuration
N/A - is a simple spring boot application

### Dependencies
C8 SaaS account

### Issues/Challenges
None - is a very naïve implementation but I hope refined it.  

### Extension lifecycle
Incubating

### Additional Context
N/A

### Maintainer Needed?
No

**Comment by xomiamoore** [comment]
Hi @marco-as-lopes! Sorry for the delay in response. Were you able to transfer your repo [following these instructions](https://github.com/camunda-community-hub/community#getting-started)?

**Comment by xomiamoore** [comment]
Closing since this is in the Hub now: https://github.com/camunda-community-hub/SaaS-Worker-Simulator :)
