### ISSUE TITLE
Pull Request

### ISSUE THREAD

**Issue by Dawenxes** [camunda-community-hub/community#3]
# Camunda Community Hub Pull Request Template

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an existing open issue)
- [ ] New feature (non-breaking change which adds functionality to an extension)
- [ ] Breaking change (fix or feature that would cause existing functionality of an extension to change)
- [ ] Documentation update (changes made to an existing piece of documentation)

## Checklist:

- [ ] My code adheres to the syntax used by this extension.
- [ ] My pull request requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **Camunda Community Hub** documentation
- [ ] I have read the **Pull Request Process** documentation
- [ ] I have added or suggested tests to cover my changes suggested in this pull request.
- [ ] All new and existing CI/CD tests passed.
- [ ] I will /assign myself this issue, and add the relevant [issue labels] to it if they are not automatically generated by Probot.
- [ ] I will tag @celanthe in a new comment on this issue if 30 days have passed since my pull request was opened and I have not received a response from the extension's Maintainer

**Comment by celanthe** [comment]
Hi @Dawenxes! 

Thank you for your PR. I was wondering if you had a specific question I might be able to assist with? I am happy to help!

Best,
Rin

**Comment by celanthe** [comment]
Hi @Dawenxes!

As I haven't heard back from you, I am going to close this issue! Please feel free to open another if there is something I can help you with.

Best,
Rin
