### ISSUE TITLE
New Community Extension - Zeebe Worker Scala Template

### ISSUE THREAD

**Issue by riccardomerolla** [camunda-community-hub/community#30]
# Camunda Community Hub Extension Proposal

Minimal template for a [Zeebe](https://github.com/camunda-cloud/zeebe) Scala [worker](https://docs.camunda.io/docs/components/concepts/job-workers/). This template adds only the bare minimum of dependencies.

### Extension description
This extension allows you to create a Scala worker with minimal dependencies easily.

### Suggested use case
For Scala 3 lovers.

### Configuration
Configuration is explained in the readme.

### Dependencies
Scala

### Issues/Challenges
None

### Extension lifecycle
Incubating

### Additional Context
The extension is currently in the repo here: [https://github.com/riccardomerolla/zeebe-worker-scala-template](https://github.com/riccardomerolla/zeebe-worker-scala-template)

### Maintainer Needed?
No

**Comment by xomiamoore** [comment]
Hi @riccardomerolla ! Sorry for the delayed reply. I've sent you an invite to join the Community Hub. After that, you can follow [these instructions](https://github.com/camunda-community-hub/community#getting-started) to transfer your extension. Please let me know if there is anything else I can help you with, and thank you for your contribution!

**Comment by xomiamoore** [comment]
Hi @riccardomerolla, it looks like you're a member now, but I couldn't find this repo inside the Community Hub. Do you need help transferring it?
