### ISSUE TITLE
Please add me as a collaborator to community hub

### ISSUE THREAD

**Issue by plungu** [camunda-community-hub/community#31]

**Comment by plungu** [comment]
What is the best way to transfer an existing project?

**Comment by mary-grace** [comment]
@plungu - Glad to hear you want to transfer something over! I just sent over an invite to join the Community Hub. Once you've accepted the invite, you can follow the instructions here: https://github.com/camunda-community-hub/community#getting-started

**Comment by xomiamoore** [comment]
Hi @plungu, looks like you're a member of the community now! Do you need help transferring any projects?

**Comment by xomiamoore** [comment]
Looks like you're all set up so I'll close this issue, but please feel free to re-open it if you have any questions!
