### ISSUE TITLE
First issue to join the Hub!

### ISSUE THREAD

**Issue by PreetiNirwal** [camunda-community-hub/community#40]
Hi there! Submitting my first issue so I can be invited to join https://github.com/camunda-community-hub/camunda-8-connectors. Thanks!

**Comment by akeller** [comment]
Pending invite for you 😄 

I also added you to the Connectors team. Once you accept the invitation, please close this issue.

**Comment by PreetiNirwal** [comment]
Accepted invite, closing issue. Thanks!
