### ISSUE TITLE
Issue to invite me

### ISSUE THREAD

**Issue by Sijoma** [camunda-community-hub/community#51]
Hey community hub maintainers 🛠️ ,
please add me here :)

**Comment by akeller** [comment]
You are in! (Actually, you were in already. Do you have access to what you need?)

**Comment by Sijoma** [comment]
Ahhh I was already in 🤦 .

I have a weird issue where I cannot pull docker images from the community-hub (zeebe-play). But it is probably unrelated as it works inside k8s. Thank you @akeller

**Comment by akeller** [comment]
Reopen this if you run into issues again, we can give you higher permissions on the repo and see if that get you what you need.
