### ISSUE TITLE
Question about new Camunda related Open Source projects

### ISSUE THREAD

**Issue by hauptmedia** [camunda-community-hub/community#52]
Hi,

I published two Camunda related Open Source projects and would like to ask if there is any interest to move these projects to Camunda Community Hub.

https://github.com/hauptmedia/zbcat
https://github.com/hauptmedia/zeebe-exporter-types

Cheers,

Julian Haupt

**Comment by xomiamoore** [comment]
Hi @hauptmedia! Absolutely, we'd love to have them here :) 

[Here are the instructions for transferring an existing repo.](https://github.com/camunda-community-hub/community/blob/main/transferring-extensions.md) When you do so, be sure to read our [Maintainer Expectations](https://github.com/camunda-community-hub/community/blob/main/maintainer-reviewer-expectations.md) and add [Shields.io badges](https://github.com/Camunda-Community-Hub/community/blob/main/extension-lifecycle.md)!

Please let me know if there is anything else I can help with!
