### ISSUE TITLE
Camunda Community Hub

### ISSUE THREAD

**Issue by gizmo84** [camunda-community-hub/community#6]
Hi there,

I would like to join the Camunda Community Hub in order to migrate the zeebe-grpc repository located at https://gitlab.com/stephane.ludwig/zeebe_python_grpc

Thanks

Stéphane

**Comment by celanthe** [comment]
Hi @gizmo84! 

Thank you so much for opening this issue! I replied to your email, and will happily invite you to join the Community Hub ASAP!

Best,
Rin

**Comment by celanthe** [comment]
Hi @gizmo84! :) I have good news! We've resolved our GitHub permissions issue, and I've sent you an invitation to join the Community Hub. I included information on how to transfer the repository in a response to your email. 

I'll leave this issue open until the repository is transferred over, just in case we need to troubleshoot anything. If you run into any issues, please don't hesitate to reach out. I am happy to help however I can.

Best,
Rin

**Comment by celanthe** [comment]
Hi @gizmo84 -- I hope today finds you well! I just wanted to circle back on this! I look forward to hearing from you!

**Comment by gizmo84** [comment]
I'm in, you can close the issue!
