### ISSUE TITLE
New community extension: Camunda Automation Platform 7 Webapps translations

### ISSUE THREAD

**Issue by tasso94** [camunda-community-hub/community#61]
# New community extension Camunda 7 Webapps translations

### Extension description

The extension provides translations in 16 different languages (e.g., Japanese, Danish, Nepali, etc.) for Camunda 7 Tasklist, Cockpit Basic/Full, and Admin.

### Suggested use case

Making the Camunda 7 Webapps available in other languages than English and German.

### Configuration

Just copy one or more of the language files to a webapp and include them in the config file as described in the [User Guide](https://docs.camunda.org/manual/latest/webapps/tasklist/configuration/#localization).

### Dependencies

None.

### Issues/Challenges

None.

### Extension lifecycle

The extension already exists but should be moved into the community hub:
https://github.com/camunda/camunda-webapp-translations/

### Additional context

None.

### Maintainer needed?

This extension is actively seeking a maintainer.

**Comment by tasso94** [comment]
Unfortunately, I cannot add any labels.

**Comment by xomiamoore** [comment]
Hi @tasso94! This is a great extension and I think it would be a great fit to have here. It's not currently officially supported by Camunda, correct? 

I sent you an invite to become a member of the Camunda Community Hub.

[This page](https://docs.github.com/en/enterprise-server@3.3/repositories/creating-and-managing-repositories/transferring-a-repository#transferring-a-repository-owned-by-your-organization) has the instructions for transferring the repo.

Once you have transferred the repo, be sure to [add the correct badges](https://github.com/Camunda-Community-Hub/community/blob/main/extension-lifecycle.md) for "maintainer wanted," Camunda Platform 7, and the correct life cycle stage.

Let me know if I can be of further assistance!

**Comment by tasso94** [comment]
Hi @xomiamoore,

The repo still has branches for old versions of Camunda 7 that contain our officially supported English language. This is why I would prefer not to transfer the repository but create a new one in the hub and move the community parts out of the repository into the hub. 

Do you think this also works? I would adjust the README in the old repo to emphasize that the repo has been moved into the community hub (+ link).

Best,
Tassilo

**Comment by xomiamoore** [comment]
@tasso94, That makes sense to me as long as the boundaries are clearly defined :) 

I went ahead and made an empty repo for this and added you as a maintainer, please add what you need and let me know if there's anything else I can help with!

https://github.com/camunda-community-hub/camunda-7-webapp-translations

I'll close this issue since I created the repo, but please re-open if you need anything or tag me in an issue in [the repo](https://github.com/camunda-community-hub/camunda-7-webapp-translations).
