### ISSUE TITLE
DMN Tester

### ISSUE THREAD

**Issue by pme123** [camunda-community-hub/community#7]
# Camunda Community Hub Extension Proposal

### Extension description

A little DMN Table tester with the following Goals:
- As a developer I want to test the DMNs that I get from the Business, even not knowing the concrete rules.
- Business people can create their own tests.
- They can easily adjust the tests to the dynamic nature of DMN Tables.

See here: https://github.com/pme123/camunda-dmn-tester 

### Suggested use case

See description.

### Configuration

All you need is a Docker Installation.

There is an example in the /demo folder with start scripts.
### Issues/Challenges

At the moment there should be none🤞

### Extension lifecycle

Phase of testing with real live DMNs.

**Comment by celanthe** [comment]
Hi @pme123! Thank you so much for this amazing extension proposal! We'd love to have this in the Community Hub! :) We're currently experiencing a GitHub permissions issue at the moment, but once that's resolved I will get back to you ASAP and invite you to join the Hub. Once that step is completed, you should be able to follow the instructions [for transferring a repository in your personal GitHub account to the Community Hub](https://github.com/camunda-community-hub/community#transferring-a-repository-in-your-personal-github-account).

Again, thank you so much for the proposal and for your wonderful contribution to Camunda! We are excited to get this into the Hub, and I'll be in touch ASAP once we've resolved the permissions issue to get the ball rolling!

**Comment by celanthe** [comment]
Hi @pme123! I've sent you an invite to join the Community Hub, and you should now be able to follow the instructions in my comment above for transferring the repository! :) I'll leave this issue open until the repo is transferred over, just in case we need to troubleshoot anything!

Please do let me know if you run into any issues. I am happy to help! 

Best,
Rin

**Comment by pme123** [comment]
Hi @celanthe, I think I did it 😉.

https://github.com/camunda-community-hub/camunda-dmn-tester

Regards Pascal

**Comment by celanthe** [comment]
Hi @pme123! You did indeed! :D This is fantastic! I'll close this issue, then! Welcome to the Camunda Community Hub! :D
