### ISSUE TITLE
Transfer of  Camunda Keycloak Identity Provider Plugin

### ISSUE THREAD

**Issue by VonDerBeck** [camunda-community-hub/community#8]
Hi there,

I would like to join the Camunda Community Hub in order to migrate the Camunda Keycloak Identity Provider Plugin located at https://github.com/camunda/camunda-bpm-identity-keycloak
I already had an invitation to this repository in April and thought I accepted it. Either I forgot to actually do it or the membership is gone meanwhile... Anyway - I would like to move my repo!

Thanks
Gunnar

**Comment by celanthe** [comment]
Hi @VonDerBeck! I've sent you an invite to join the Community Hub! :) For now, I'll leave this issue open until Keycloak has been migrated over. 

If you have any questions, please don't hesitate to reach out! I am happy to help however I can.

**Comment by VonDerBeck** [comment]
Hi @celanthe,

invitation has worked. Thanks a lot. 👍 

Transferring the repository itself from https://github.com/camunda/camunda-bpm-identity-keycloak to its new home - is that something you do? Since it has been located under Camunda's GitHub location, I'm not the owner any more, just a contributor.
Once this is done and I have access rights to the new location, I'm able to continue for myself.

Thanks
Gunnar

**Comment by celanthe** [comment]
Hi @VonDerBeck!

I can get the repository transferred over to its new home in short order! :) Not to worry! Will update in this thread once that's been completed.

Thanks so much!

--Rin

**Comment by VonDerBeck** [comment]
@celanthe - no need to hurry, I have a long weekend and won't continue with that before next monday ;-)
Thank you so much for your support!
Gunnar

**Comment by VonDerBeck** [comment]
Hi @celanthe,
thanks for transferring the repository. Access works so far.

I have a question on how to perform releases. According to Step 1 and Step 2  of https://github.com/camunda-community-hub/community/blob/main/RELEASE.MD I have to draft a new release in GitHub. This will then trigger `mvn release:prepare release:perform`. 

- In order to run the Maven release plugin the typical usage is something like `release:prepare release:perform 
   -DreleaseVersion=${releaseVersion} -DdevelopmentVersion=${developmentVersion}`
- Where do you get the release version and new development version from? I guess that the actual release version is the version I created in GitHub? What about the new development version?

Thanks
Gunnar

**Comment by VonDerBeck** [comment]
Hello @celanthe ,

thanks again for your support. Everything works fine - including the release :-)

In the repository itself I have:
* adjusted the README
* added a CONTRIBUTING.md
* adopted labels from https://github.com/camunda-community-hub/template-repo
* created a pull request template according to https://github.com/camunda-community-hub/template-repo

Hope this covers the most important things. If you think of anything else, please let me know. As the transfer itself is donee, we can indeed close this issue.

Gunnar
