### ISSUE TITLE
New Community Extension - zeebe-clickhouse-exporter

### ISSUE THREAD

**Issue by skayliu** [camunda-community-hub/community#81]
# Camunda Community Hub Extension Proposal
Hi there,

I'd like to join the Camunda Community Hub in order to migrate the [zeebe-clickhouse-exporter](https://github.com/skayliu/zeebe-clickhouse-exporter) repository.

### Extension description
With this exporter, we can export records from Zeebe to ClickHouse and query data from ClickHouse use our own program language.

The project can be found here: https://github.com/skayliu/zeebe-clickhouse-exporter

### Suggested use case
None

### Configuration
Configuration is explained in the readme.

### Dependencies
* zeebe-exporter-api
* clickhouse-jdbc

### Issues/Challenges
None

## Extension lifecycle
Zeebe

## Additional Context
None

## Maintainer Needed?
No

**Comment by xomiamoore** [comment]
Hi @skayliu, we'd love to have this in the Community Hub!

I sent an invitation to become a member of the Community Hub, once you accept it you should be able to transfer the repo in [following these instructions.](https://github.com/camunda-community-hub/community/blob/main/transferring-extensions.md)

Let me know if there's anything else I can help with!

**Comment by skayliu** [comment]
Hey, @xomiamoore, It's done. Thank you very much. 🌹
